# Generated by Django 5.2.4 on 2025-07-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='food_type',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
